version: '20.10.20'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../.env
    restart: always

  # backend:
  #   image: pleasurelf/foodgram:latest
  #   depends_on:
  #     - db
  #   volumes:
  #     - static_value:/app/static/
  #     - media_value:/app/media/
  #   env_file:
  #     - ./.env
  #   restart: always

  backend:
    build:
      context: ../
      dockerfile: backend/Dockerfile
    restart: always
    ports:
     - "8000:8000"
    # image: aaaa dockerhub
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ../.env 

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/django_files/static/
      - media_value:/var/html/django_files/media/
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  foodgram_docker_volume:
    external: false