version: '20.10.20'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../.env
    restart: always

  backend:
    image: pleasurelf/foodgram:latest
    depends_on:
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ../.env 
    restart: always

  frontend:
    image: pleasurelf/foodgram_frontend:latest
    volumes:
      - frontend_static:/app/result_build/build
    env_file:
      - ../.env 
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_static:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/django_files/static/
      - media_value:/var/html/django_files/media/
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  frontend_static:
  foodgram_docker_volume:
    external: false
