# Generated by Django 4.1.3 on 2022-11-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('unit', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='recipy',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='recipy',
            name='tag',
            field=models.ManyToManyField(blank=True, to='recipes.tag'),
        ),
    ]
