# Generated by Django 4.1.3 on 2022-12-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientstorecipe',
            old_name='ingredient',
            new_name='name',
        ),
    ]
