# Generated by Django 4.1.3 on 2022-12-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_ingredient_ingredientstorecipe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='ingredientstorecipe',
            old_name='name',
            new_name='ingredient',
        ),
    ]
