# Generated by Django 4.1.3 on 2022-12-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_unit_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipy',
            name='is_favorite',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
