# Generated by Django 4.1.3 on 2022-11-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_amount_tag_hex_tag_slug_alter_tag_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipy',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='recipy',
            name='cooking_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='recipy',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='recipes.ingredient'),
        ),
    ]
