# Generated by Django 4.1.3 on 2022-12-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipy_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipy',
            name='pub_date',
        ),
    ]
