# Generated by Django 4.1.3 on 2022-12-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipy_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='recipes/media/txt/', verbose_name='Список покупок'),
        ),
    ]
