# Generated by Django 4.1.3 on 2022-12-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_shoppingcart_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='file',
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_items', to='recipes.shoppingcart')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_to_buy', to='recipes.ingredient')),
            ],
        ),
    ]
