# Generated by Django 4.1.3 on 2022-12-08 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_ingredientstorecipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientstorecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_to_recipe', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientstorecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_with_ingredients', to='recipes.recipy', verbose_name='Рецепт'),
        ),
    ]
