# Generated by Django 4.1.3 on 2022-12-08 23:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0012_alter_ingredientstorecipe_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipy',
            new_name='Recipe',
        ),
    ]
