# Generated by Django 4.1.3 on 2022-12-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_following_alter_subscription_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-user',), 'verbose_name': 'Подписки', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-username',), 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
